blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/MathiasPaulenko/behave-comments/discussions
    about: Ask questions and start discussions here.
